#version: '1'

vsal:
  container_name: vsal
  image: vsal.garvan.org.au:5000/vsal:latest
  links:
    - clindata
    - ocga
  ports:
    - 8080:8080
    - 8443:8443

clindata:
  container_name: clindata
  image: vsal.garvan.org.au:5000/clindata:latest
  links:
    - clindb:clindb
  ports:
    - 4080:8080

clindb:
  container_name: clindb
  image: vsal.garvan.org.au:5000/clindb:latest
  ports:
    - 3306:3306

ocga:
  container_name: ocga
  image: vsal.garvan.org.au:5000/ocga.deploy:rc1.1
  volumes:
    - /data/catalog:/data/catalog
    - /data/db:/data/db
  ports:
    - 9000:8080
    - 27017:27017

