#version: '1'

# UAT
vsal.uat:
  container_name: vsal.uat
  image: vsal
  links:
    - clindata.uat:clindata
    - ocga.uat:ocga
  ports:
    - 8080:8080

clindata.uat:
  container_name: clindata.uat
  image: clindata
  links:
    - clindb.uat:clindb

clindb.uat:
  container_name: clindb.uat
  image: clindb

ocga.uat:
  container_name: ocga.uat
  image: ocga.deploy
  volumes:
    - /data/uat/catalog:/data/catalog
    - /data/uat/db:/data/db

# UAT debug
vsal.uat.debug:
  container_name: vsal.uat.debug
  image: vsal
  links:
    - clindata.uat.debug:clindata
    - ocga.uat.debug:ocga
  ports:
    - 8080:8080

clindata.uat.debug:
  container_name: clindata.uat.debug
  image: clindata
  links:
    - clindb.uat.debug:clindb
  ports:
    - 7080:8080

clindb.uat.debug:
  container_name: clindb.uat.debug
  image: clindb
  ports:
    - 3306:3306

ocga.uat.debug:
  container_name: ocga.uat.debug
  image: ocga.deploy
  volumes:
    - /data/uat/catalog:/data/catalog
    - /data/uat/db:/data/db
  ports:
    - 9000:8080
    - 27017:27017
